Repository vavr-io/vavr, pull requests merged in 2018-10, with the labels that each got.

#2306 Added hints on how to use Vavr
  README.md
Labels: documentation, «non-public»

#2307 Removed Option.toTry() in favor of Option.toTry(Supplier)
  vavr-control/src/main/java/io/vavr/control/Option.java
  vavr-control/src/test/java/io/vavr/control/OptionTest.java
Labels: design/refactoring/improvement, «vavr-control» (obsolete)

#2310 Fix confusing enforcer plugin error message
  pom.xml
Labels: bug, build/infrastructure/ide, «non-public»

#2312 Deprecate Value.toJavaArray(Class<T>), add toJavaArray(IntFunction<T[]>)
  vavr-benchmark/src/test/java/io/vavr/collection/MapBenchmark.java
  vavr-benchmark/src/test/java/io/vavr/control/LazyBenchmark.java
  vavr-test/src/main/java/io/vavr/test/Gen.java
  vavr/src/main/java/io/vavr/Value.java
  vavr/src/test/java/io/vavr/AbstractValueTest.java
  vavr/src/test/java/io/vavr/collection/AbstractTraversableTest.java
  vavr/src/test/java/io/vavr/collection/CharSeqTest.java
Labels: !BACK-COMPAT, design/refactoring/improvement, «cross cutting»

#2319 Java8 compat
  .travis.yml
  README.md
  build.gradle
  settings.gradle
  src/main/java/io/vavr/collection/IndexedSeq.java
  src/main/java/io/vavr/collection/Iterable.java
  src/main/java/io/vavr/collection/Iterator.java
  src/main/java/io/vavr/collection/LinearSeq.java
  src/main/java/io/vavr/collection/Map.java
  src/main/java/io/vavr/collection/Seq.java
  src/main/java/io/vavr/collection/Set.java
  src/main/java/io/vavr/collection/SortedMap.java
  src/main/java/io/vavr/collection/SortedSet.java
  src/main/java/io/vavr/collection/Tuple2.java
  src/main/java/io/vavr/control/CheckedConsumer.java
  src/main/java/io/vavr/control/CheckedFunction.java
  src/main/java/io/vavr/control/CheckedPredicate.java
  src/main/java/io/vavr/control/CheckedRunnable.java
  src/main/java/io/vavr/control/Either.java
  src/main/java/io/vavr/control/NonFatalException.java
  src/main/java/io/vavr/control/Option.java
  src/main/java/io/vavr/control/Try.java
  src/main/java/io/vavr/control/package-info.java
  src/test/java/io/vavr/collection/IterableTest.java
  src/test/java/io/vavr/control/CheckedConsumerTest.java
  src/test/java/io/vavr/control/CheckedFunctionTest.java
  src/test/java/io/vavr/control/CheckedPredicateTest.java
  src/test/java/io/vavr/control/CheckedRunnableTest.java
  src/test/java/io/vavr/control/EitherTest.java
  src/test/java/io/vavr/control/OptionTest.java
  src/test/java/io/vavr/control/TryTest.java
  vavr-collection/build.gradle
  vavr-collection/src/main/java/module-info.java
  vavr-control/build.gradle
  vavr-control/src/main/java/module-info.java
Labels: build/infrastructure/ide
